const LRL: any = {
  ES: {
    register: "Registrarse",
    logIn: "Iniciar Sesión",
    name: "Nombre",
    lastName: "Apellido",
    email: "Correo",
    password: "Contraseña",
    phone: "Teléfono",
    formErrorRequired: "* Este campo es obligatorio",
    formErrorName: "* Por favor ingrese su nombre completo",
    formErrorEmail: "* Por favor ingrese un mail válido",
    formErrorPassword1: "* La contraseña debe contener un mínimo de ",
    formErrorPassword2: " caracteres",
    legalMessageAccept: "Al crear una cuenta estas aceptando los",
    legalMessageTerms: "Términos del servicio",
    and: "y",
    legalMessagePolitics: "Política de privacidad",
    forgotPassword:"¿Olvidaste tu contraseña?",
    birthday: 'Fecha nacimiento',
    gender: 'Género',
  },
  EN: {
    register: "Sign Up",
    logIn: "Log In",
    name: "Name ",
    lastName: "Lastname",
    email: "Email",
    password: "Password",
    phone: "Phone",
    formErrorRequired: "* This field is required",
    formErrorName: "* Please enter your full name",
    formErrorEmail: "* Please enter a valid email",
    formErrorPassword1: "* Password must contain a minimum of ",
    formErrorPassword2: "* characters",
    legalMessageAccept: "By creating an account you are accepting the",
    legalMessageTerms: "Terms of Service",
    and: "and",
    legalMessagePolitics: "Privacy Policy",
    forgotPassword: "¿Forgot your password?",
    birthday: 'Date of birth',
    gender: 'Gender'
  },
};
export default LRL;

