const RDL: any = {
  ES: {
    saveButton: 'Guardar',
    portions: 'Porciones',
    whatYouNeed: 'Lo que necesitas',
    myNotes: 'Mis notas',
    add: 'Añadir',
    nutritionInfo: 'Información Nutricional',
    visitProfile: 'Visitar perfil',
    chooseDay: 'Elija el día que quiera agregarlo al menú:',
    selectDay: 'Seleccionar fecha',
    chooseFood: 'Elija comida del día:',
    selectFood: 'Seleccionar comida',
    chooseCategory: 'Elija categoría que desee agregar receta:',
    selectCategory: 'Seleccionar categoría',
  },
  EN: {
    saveButton: 'Save',
    portions: 'Portions',
    whatYouNeed: 'What you need',
    myNotes: 'My notes',
    add: 'Add',
    nutritionInfo: 'Nutritional Information',
    visitProfile: 'Visit profile',
    chooseDay: 'Choose the day you want to add it to the menu:',
    selectDay: 'Select date',
    chooseFood: 'Choose meal of the day:',
    selectFood: 'Select food',
    chooseCategory: 'Choose the category you want to add a recipe to:',
    selectCategory: 'Select category ',
  },
};
export default RDL;
