const RL: any = {
  ES: {
    register: 'Registrarse',
    name: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo',
    password: 'Contraseña',
    formErrorRequired: '* Este campo es obligatorio',
    formErrorName: '* Por favor ingrese su nombre completo',
    formErrorEmail: '* Por favor ingrese un mail válido',
    formErrorPassword1: '* La contraseña debe contener un mínimo de ',
    formErrorPassword2: ' caracteres',
    legalMessageAccept: 'Al crear una cuenta estas aceptando los',
    legalMessageTerms: 'Términos del servicio',
    and: 'y',
    legalMessagePolitics: 'Política de privacidad',
  },
  EN: {
    register: 'Sign Up',
    name: 'Name ',
    lastName: 'Lastname',
    email: 'Email',
    password: 'Password',
    formErrorRequired: '* This field is required',
    formErrorName: '* Please enter your full name',
    formErrorEmail: '* Please enter a valid email',
    formErrorPassword1: '* Password must contain a minimum of ',
    formErrorPassword2: '* characters',
    legalMessageAccept: 'By creating an account you are accepting the',
    legalMessageTerms: 'Terms of Service',
    and: 'and',
    legalMessagePolitics: 'Privacy Policy',
  },
};
export default RL;
